### ISSUE TITLE
!lunch returns dinner suggestions

### ISSUE THREAD

**Issue by sdepew** [LEXmono/q#69] opened 2017-12-07 19:02 UTC
Stephen [2:01 PM] 
!lunch

Q APP [2:01 PM] 
What about these for `dinner` in Herndon, VA:
Hen Penny
Guapo's Rotisserie Chicken & Tex Mex Grill
Charcoal Kabob
Kumo Sushi
Cooper's Hawk Winery & Restaurants

**Comment by LEXmono** [comment] 2017-12-07 20:35
This is not a bug. `!lunch` is just an alias for `!food`. `!food`  returns things for certain times of the day. 

[Alias](https://github.com/LEXmono/q/blob/master/bot/commands/food.py#L143) | [Time Logic](https://github.com/LEXmono/q/blob/master/bot/commands/food.py#L154)

We can drop the bug tag and add separate functions to only return those terms if you want?

**Comment by LEXmono** [comment] 2017-12-15 01:28
@sdepew - Closing this. Add a feature if we need to split these apart.

**Closed by LEXmono** 2017-12-15 01:28 UTC
Labels: bug
